#!/usr/bin/env python3
"""
OPNsense HAProxy Import Script

Imports Sophos WAF configuration into OPNsense HAProxy using the local pysense API.
Uses the JSON files generated by sophos_parser.py and the frontend_backend_mapping.json.

Usage:
    # Dry run - shows what would be created
    python opnsense_haproxy_import.py --dry-run

    # Import to OPNsense
    python opnsense_haproxy_import.py --url https://opnsense.local:444/api --key YOUR_KEY --secret YOUR_SECRET

    # Import only enabled items
    python opnsense_haproxy_import.py --url https://opnsense.local:444/api --key KEY --secret SECRET --enabled-only
"""

import sys
import json
import re
import argparse
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional

# Add local pysense to path
sys.path.insert(0, str(Path(__file__).parent))

from pysense.client import Client
from pysense.pydantic.Acl import Acl
from pysense.pydantic.Action import Action
from pysense.pydantic.Server import Server
from pysense.pydantic.Backend import Backend
from pysense.pydantic.Frontend import Frontend
from pysense.pydantic.SearchRequest import SearchRequest


def slugify(name: str, max_length: int = 32) -> str:
    """Convert name to valid HAProxy/OPNsense identifier."""
    slug = re.sub(r'[^a-zA-Z0-9_-]', '_', name)
    slug = re.sub(r'_+', '_', slug)
    return slug.strip('_').lower()[:max_length]


@dataclass
class ImportResult:
    """Track import results and UUIDs for linking entities."""
    servers: dict = field(default_factory=dict)      # ref_id -> uuid
    backends: dict = field(default_factory=dict)     # ref_id -> uuid
    acls: dict = field(default_factory=dict)         # name -> uuid
    actions: dict = field(default_factory=dict)      # name -> uuid
    frontends: dict = field(default_factory=dict)    # ref_id -> uuid
    errors: list = field(default_factory=list)
    warnings: list = field(default_factory=list)


class OPNsenseHAProxyImporter:
    """Import Sophos WAF configuration into OPNsense HAProxy."""

    def __init__(self, input_dir: str, mapping_file: str,
                 client: Optional[Client] = None, dry_run: bool = True,
                 enabled_only: bool = False):
        self.input_dir = Path(input_dir)
        self.mapping_file = mapping_file
        self.client = client
        self.dry_run = dry_run
        self.enabled_only = enabled_only
        self.result = ImportResult()

        # Load data
        self.frontends = self._load_json('waf_frontends.json')
        self.locations = self._load_json('waf_locations.json')
        self.backends = self._load_json('waf_backends.json')
        self.mapping = self._load_mapping()

        # Build lookups
        self.frontend_lookup = {f['ref_id']: f for f in self.frontends}
        self.location_lookup = {l['ref_id']: l for l in self.locations}
        self.backend_lookup = {b['ref_id']: b for b in self.backends}

    def _load_json(self, filename: str) -> list:
        """Load JSON file from input directory."""
        filepath = self.input_dir / filename
        if not filepath.exists():
            print(f"Warning: {filepath} not found")
            return []
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)

    def _load_mapping(self) -> dict:
        """Load frontend-backend mapping file."""
        with open(self.mapping_file, 'r', encoding='utf-8') as f:
            return json.load(f)

    def import_all(self):
        """Run the complete import process."""
        print("=" * 60)
        print("OPNsense HAProxy Import")
        print("=" * 60)

        if self.dry_run:
            print("MODE: Dry run (no changes will be made)")
        else:
            print("MODE: Live import")

        if self.enabled_only:
            print("FILTER: Only enabled items")

        print()

        # Step 1: Import servers (backend targets)
        print("Step 1: Creating Servers...")
        self._import_servers()

        # Step 2: Import backends (server pools)
        print("\nStep 2: Creating Backends...")
        self._import_backends()

        # Step 3: Import ACLs
        print("\nStep 3: Creating ACLs...")
        self._import_acls()

        # Step 4: Import actions
        print("\nStep 4: Creating Actions...")
        self._import_actions()

        # Step 5: Import/update frontends
        print("\nStep 5: Creating Frontends...")
        self._import_frontends()

        # Step 6: Test and apply
        if not self.dry_run:
            print("\nStep 6: Testing and applying configuration...")
            self._apply_configuration()

        # Summary
        self._print_summary()

        return self.result

    def _import_servers(self):
        """Create server entries for each backend target."""
        for backend in self.backends:
            if self.enabled_only and not backend.get('enabled', True):
                continue

            host = backend.get('host', {})
            address = host.get('address', '127.0.0.1')
            port = backend.get('port', 80)
            ssl = backend.get('ssl', False)
            name = f"srv_{slugify(backend['name'])}"

            print(f"  - {name}: {address}:{port}", end="")

            if ssl:
                print(" [SSL]", end="")
            if not backend.get('enabled', True):
                print(" [DISABLED]", end="")

            if self.dry_run:
                print(" (dry run)")
                self.result.servers[backend['ref_id']] = f"dry-run-{name}"
            else:
                try:
                    # Use getcreate_server pattern from pysense
                    # Remove spaces and special chars from name for API compatibility
                    clean_name = backend['name'].replace(' ', '-').replace('_', '-')
                    domain_safe = self.client.domain_name_safe(clean_name)
                    server_uuid = self.client.getcreate_server(
                        domain=clean_name,
                        domain_name_safe=domain_safe,
                        ip=address,
                        port=port
                    )
                    self.result.servers[backend['ref_id']] = str(server_uuid)
                    print(f" -> {server_uuid}")
                except Exception as e:
                    print(f" ERROR: {e}")
                    self.result.errors.append(f"Server {name}: {e}")

    def _import_backends(self):
        """Create backend pools for each location."""
        for location in self.locations:
            if self.enabled_only and not location.get('enabled', True):
                continue

            # Get linked servers and their names for better backend naming
            server_uuids = []
            server_names = []
            for be_ref in location.get('backends', []):
                be_ref_id = be_ref.get('ref_id', '')
                if be_ref_id in self.result.servers:
                    server_uuids.append(self.result.servers[be_ref_id])
                # Get server name from backend lookup
                be_info = self.backend_lookup.get(be_ref_id)
                if be_info:
                    server_names.append(be_info['name'])

            # Create a descriptive backend name using server name
            if server_names:
                # Use first server name as base
                base_name = server_names[0].replace(' ', '-')
                # Add path suffix if it's not just "/"
                path = location.get('path', '/')
                if path and path != '/':
                    path_suffix = slugify(path.strip('/'))
                    backend_name = f"{base_name}_{path_suffix}"
                else:
                    backend_name = base_name
            else:
                backend_name = slugify(location['name'])

            name = f"be_{slugify(backend_name)}"
            print(f"  - {name}: {location['path']}", end="")

            if not location.get('enabled', True):
                print(" [DISABLED]", end="")

            if self.dry_run:
                print(f" (dry run, servers: {len(server_uuids)})")
                self.result.backends[location['ref_id']] = f"dry-run-{name}"
            else:
                try:
                    # Clean backend name for API compatibility
                    clean_name = backend_name.replace(' ', '-')
                    domain_safe = self.client.domain_name_safe(clean_name)
                    # Use first server - filter out None values
                    valid_server_uuids = [u for u in server_uuids if u and u != 'None']
                    server_uuid = valid_server_uuids[0] if valid_server_uuids else None
                    if server_uuid:
                        backend_uuid = self.client.getcreate_backend(
                            domain=clean_name,
                            domain_name_safe=domain_safe,
                            server_uuid=server_uuid
                        )
                        self.result.backends[location['ref_id']] = str(backend_uuid)
                        print(f" -> {backend_uuid}")
                    else:
                        print(" SKIPPED (no valid servers)")
                        self.result.warnings.append(f"Backend {name}: no valid servers linked")
                except Exception as e:
                    print(f" ERROR: {e}")
                    self.result.errors.append(f"Backend {name}: {e}")

    def _import_acls(self):
        """Create ACLs for host matching and path routing."""
        for fe_ref, fe_mapping in self.mapping.get('mappings', {}).items():
            if self.enabled_only and not fe_mapping.get('enabled', True):
                continue

            frontend_name = fe_mapping.get('frontend_name', '')

            # Create host ACLs for each domain
            for domain in fe_mapping.get('domains', []):
                domain_safe = self.client.domain_name_safe(domain) if self.client else domain.replace('.', '_dot_')
                acl_name = f"acl_{domain_safe}"
                print(f"  - {acl_name}: Host = {domain}", end="")

                if self.dry_run:
                    print(" (dry run)")
                    self.result.acls[acl_name] = f"dry-run-{acl_name}"
                else:
                    try:
                        acl_search = self.client.haproxy_settings_searchAcls(
                            SearchRequest.search(acl_name)
                        )
                        acl_uuid = self.client.getcreate_acl(
                            acl_search,
                            Acl(
                                name=acl_name,
                                hdr=domain,
                                hdr_beg=domain,
                                expression=Acl.AclsAclExpressionEnum.HDR,
                                description=f"Sophos frontend: {frontend_name}"
                            )
                        )
                        self.result.acls[acl_name] = str(acl_uuid)
                        print(f" -> {acl_uuid}")
                    except Exception as e:
                        print(f" ERROR: {e}")
                        self.result.errors.append(f"ACL {acl_name}: {e}")

            # Create path ACLs for path-based routing
            for rule in fe_mapping.get('path_rules', []):
                path = rule.get('path', '/')
                if path != '/':
                    acl_name = f"acl_path_{slugify(path)}"
                    print(f"  - {acl_name}: path_beg = {path}", end="")

                    if self.dry_run:
                        print(" (dry run)")
                        self.result.acls[acl_name] = f"dry-run-{acl_name}"
                    else:
                        try:
                            acl_search = self.client.haproxy_settings_searchAcls(
                                SearchRequest.search(acl_name)
                            )
                            acl_uuid = self.client.getcreate_acl(
                                acl_search,
                                Acl(
                                    name=acl_name,
                                    path_beg=path,
                                    expression=Acl.AclsAclExpressionEnum.PATH_BEG,
                                    description=f"Path rule for {frontend_name}"
                                )
                            )
                            self.result.acls[acl_name] = str(acl_uuid)
                            print(f" -> {acl_uuid}")
                        except Exception as e:
                            print(f" ERROR: {e}")
                            self.result.errors.append(f"ACL {acl_name}: {e}")

        # Create ACLs for allowed networks (IP-based access control)
        for location in self.locations:
            if self.enabled_only and not location.get('enabled', True):
                continue

            allowed = location.get('allowed_networks', [])
            if allowed and not any(n.get('name') == 'Any' for n in allowed):
                for net in allowed:
                    addr = net.get('address', '')
                    mask = net.get('netmask', '')
                    if addr and addr != '0.0.0.0':
                        cidr = f"{addr}/{mask}" if mask else addr
                        acl_name = f"acl_src_{slugify(location['name'])}_{slugify(addr)}"
                        print(f"  - {acl_name}: src = {cidr}", end="")

                        if self.dry_run:
                            print(" (dry run)")
                            self.result.acls[acl_name] = f"dry-run-{acl_name}"
                        else:
                            try:
                                acl_search = self.client.haproxy_settings_searchAcls(
                                    SearchRequest.search(acl_name)
                                )
                                acl_uuid = self.client.getcreate_acl(
                                    acl_search,
                                    Acl(
                                        name=acl_name,
                                        src=cidr,
                                        expression=Acl.AclsAclExpressionEnum.SRC,
                                        description=f"Allowed network for {location['name']}"
                                    )
                                )
                                self.result.acls[acl_name] = str(acl_uuid)
                                print(f" -> {acl_uuid}")
                            except Exception as e:
                                print(f" ERROR: {e}")
                                self.result.errors.append(f"ACL {acl_name}: {e}")

    def _import_actions(self):
        """Create routing actions that link ACLs to backends."""
        for fe_ref, fe_mapping in self.mapping.get('mappings', {}).items():
            if self.enabled_only and not fe_mapping.get('enabled', True):
                continue

            frontend_name = fe_mapping.get('frontend_name', '')
            default_backend_ref = fe_mapping.get('default_backend')

            if not default_backend_ref:
                self.result.warnings.append(f"Frontend {frontend_name}: no default_backend configured")
                continue

            # Get backend UUID
            backend_uuid = self.result.backends.get(default_backend_ref)
            if not backend_uuid:
                self.result.warnings.append(f"Frontend {frontend_name}: backend {default_backend_ref} not found")
                continue

            # Create routing action for each domain
            for domain in fe_mapping.get('domains', []):
                domain_safe = self.client.domain_name_safe(domain) if self.client else domain.replace('.', '_dot_')
                action_name = f"action_{domain_safe}"
                acl_name = f"acl_{domain_safe}"
                acl_uuid = self.result.acls.get(acl_name)

                print(f"  - {action_name}: route to backend", end="")

                if self.dry_run:
                    print(" (dry run)")
                    self.result.actions[action_name] = f"dry-run-{action_name}"
                else:
                    try:
                        action_uuid = self.client.getcreate_action(
                            Action(
                                name=action_name,
                                type=Action.ActionsActionTypeEnum.USE_BACKEND,
                                use_backend=str(backend_uuid),
                                linkedAcls=[str(acl_uuid)] if acl_uuid else [],
                                description=f"Route {domain} to {fe_mapping.get('default_backend_name', '')}"
                            )
                        )
                        self.result.actions[action_name] = str(action_uuid)
                        print(f" -> {action_uuid}")
                    except Exception as e:
                        print(f" ERROR: {e}")
                        self.result.errors.append(f"Action {action_name}: {e}")

            # Create actions for path-based routing rules
            for rule in fe_mapping.get('path_rules', []):
                path = rule.get('path', '/')
                rule_backend_ref = rule.get('backend')
                rule_backend_uuid = self.result.backends.get(rule_backend_ref)

                if not rule_backend_uuid:
                    continue

                action_name = f"action_path_{slugify(frontend_name)}_{slugify(path)}"
                acl_name = f"acl_path_{slugify(path)}"
                acl_uuid = self.result.acls.get(acl_name)

                print(f"  - {action_name}: route {path} to backend", end="")

                if self.dry_run:
                    print(" (dry run)")
                    self.result.actions[action_name] = f"dry-run-{action_name}"
                else:
                    try:
                        action_uuid = self.client.getcreate_action(
                            Action(
                                name=action_name,
                                type=Action.ActionsActionTypeEnum.USE_BACKEND,
                                use_backend=str(rule_backend_uuid),
                                linkedAcls=[str(acl_uuid)] if acl_uuid else [],
                                description=f"Route {path} for {frontend_name}"
                            )
                        )
                        self.result.actions[action_name] = str(action_uuid)
                        print(f" -> {action_uuid}")
                    except Exception as e:
                        print(f" ERROR: {e}")
                        self.result.errors.append(f"Action {action_name}: {e}")

    def _import_frontends(self):
        """Create or update frontend configurations."""
        for frontend in self.frontends:
            if self.enabled_only and not frontend.get('enabled', True):
                continue

            fe_mapping = self.mapping.get('mappings', {}).get(frontend['ref_id'], {})
            name = f"fe_{slugify(frontend['name'])}"

            address = frontend.get('address', {})
            bind_addr = address.get('address', '0.0.0.0')
            bind_port = frontend.get('port', 443)

            print(f"  - {name}: {bind_addr}:{bind_port}", end="")

            if not frontend.get('enabled', True):
                print(" [DISABLED]", end="")

            # Collect action UUIDs for this frontend
            action_uuids = []
            for domain in fe_mapping.get('domains', []):
                domain_safe = self.client.domain_name_safe(domain) if self.client else domain.replace('.', '_dot_')
                action_name = f"action_{domain_safe}"
                if action_name in self.result.actions:
                    action_uuids.append(self.result.actions[action_name])

            for rule in fe_mapping.get('path_rules', []):
                path = rule.get('path', '/')
                action_name = f"action_path_{slugify(frontend['name'])}_{slugify(path)}"
                if action_name in self.result.actions:
                    action_uuids.append(self.result.actions[action_name])

            # Determine SSL mode
            is_https = frontend.get('type') == 'https'

            if self.dry_run:
                print(f" (dry run, actions: {len(action_uuids)}, ssl: {is_https})")
                self.result.frontends[frontend['ref_id']] = f"dry-run-{name}"
            else:
                try:
                    # Check if frontend already exists
                    existing_frontend = self.client.find_frontend(name)

                    if existing_frontend:
                        # Update existing frontend with new actions
                        fe = self.client.haproxy_settings_getFrontend(str(existing_frontend))
                        for action_uuid in action_uuids:
                            if action_uuid not in fe.linkedActions:
                                fe.linkedActions.append(action_uuid)
                        self.client.haproxy_settings_setFrontend(str(existing_frontend), fe)
                        self.result.frontends[frontend['ref_id']] = str(existing_frontend)
                        print(f" -> updated {existing_frontend}")
                    else:
                        # Create new frontend
                        bind = f"{bind_addr}:{bind_port}"
                        result = self.client.haproxy_settings_addFrontend(
                            name=name,
                            bind=[bind],
                            actions=action_uuids,
                            description=f"Sophos: {frontend['name']} - Domains: {', '.join(fe_mapping.get('domains', []))}"
                        )
                        self.result.frontends[frontend['ref_id']] = result.uuid
                        print(f" -> {result.uuid}")
                except Exception as e:
                    print(f" ERROR: {e}")
                    self.result.errors.append(f"Frontend {name}: {e}")

    def _apply_configuration(self):
        """Test and apply HAProxy configuration."""
        if self.dry_run or not self.client:
            print("  Skipped (dry run)")
            return

        try:
            print("  Testing and restarting HAProxy...")
            self.client.restart_if_possible()
            print("  Done!")
        except Exception as e:
            print(f" ERROR: {e}")
            self.result.errors.append(f"Apply configuration: {e}")

    def _print_summary(self):
        """Print import summary."""
        print()
        print("=" * 60)
        print("IMPORT SUMMARY")
        print("=" * 60)
        print(f"Servers created:   {len(self.result.servers)}")
        print(f"Backends created:  {len(self.result.backends)}")
        print(f"ACLs created:      {len(self.result.acls)}")
        print(f"Actions created:   {len(self.result.actions)}")
        print(f"Frontends created: {len(self.result.frontends)}")

        if self.result.warnings:
            print()
            print("WARNINGS:")
            for warning in self.result.warnings:
                print(f"  - {warning}")

        if self.result.errors:
            print()
            print("ERRORS:")
            for error in self.result.errors:
                print(f"  - {error}")

        if self.dry_run:
            print()
            print("This was a DRY RUN. No changes were made.")
            print("Run without --dry-run to import to OPNsense.")


def test_connection(client: Client):
    """Test connection to OPNsense and show existing HAProxy config."""
    print("Testing connection to OPNsense...")
    print()

    try:
        servers = client.haproxy_settings_searchServers()
        print(f"Existing Servers ({len(servers.rows)}):")
        for s in servers.rows:
            # Get full server details for address/port
            try:
                full_server = client.haproxy_settings_getServer(str(s.uuid))
                print(f"  - {s.name}: {full_server.address}:{full_server.port}")
            except:
                print(f"  - {s.name}")
    except Exception as e:
        print(f"Error listing servers: {e}")

    try:
        backends = client.haproxy_settings_searchBackend()
        print(f"\nExisting Backends ({len(backends.rows)}):")
        for b in backends.rows:
            print(f"  - {b.name}")
    except Exception as e:
        print(f"Error listing backends: {e}")

    try:
        frontends = client.haproxy_settings_searchFrontends()
        print(f"\nExisting Frontends ({len(frontends.rows)}):")
        for f in frontends.rows:
            print(f"  - {f.name}")
    except Exception as e:
        print(f"Error listing frontends: {e}")

    print()


def main():
    parser = argparse.ArgumentParser(
        description='Import Sophos WAF configuration into OPNsense HAProxy',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Dry run - shows what would be created
  python opnsense_haproxy_import.py --dry-run

  # Test connection only
  python opnsense_haproxy_import.py --test --url https://opnsense:444/api --key KEY --secret SECRET

  # Import to OPNsense
  python opnsense_haproxy_import.py --url https://opnsense:444/api --key KEY --secret SECRET

  # Import only enabled items
  python opnsense_haproxy_import.py --url https://opnsense:444/api --key KEY --secret SECRET --enabled-only
        """
    )

    parser.add_argument('--input-dir', default='output',
                        help='Directory containing WAF JSON files (default: output)')
    parser.add_argument('--mapping', default='frontend_backend_mapping.json',
                        help='Frontend-backend mapping file (default: frontend_backend_mapping.json)')

    parser.add_argument('--url', help='OPNsense API URL (e.g., https://opnsense:444/api)')
    parser.add_argument('--key', help='OPNsense API key')
    parser.add_argument('--secret', help='OPNsense API secret')

    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be imported without making changes')
    parser.add_argument('--enabled-only', action='store_true',
                        help='Only import enabled items')
    parser.add_argument('--test', action='store_true',
                        help='Test connection only, show existing config')
    parser.add_argument('--debug', action='store_true',
                        help='Enable debug output')

    args = parser.parse_args()

    # Determine if dry run
    dry_run = args.dry_run or not (args.url and args.key and args.secret)

    # Create client if credentials provided
    client = None
    if args.url and args.key and args.secret:
        client = Client(
            base_url=args.url,
            api_key=args.key,
            api_secret=args.secret,
            verify_cert=False
        )
        if args.debug:
            client.debug = True

    # Test connection only
    if args.test:
        if not client:
            print("Error: --url, --key, and --secret required for --test")
            return
        test_connection(client)
        return

    # Run import
    importer = OPNsenseHAProxyImporter(
        input_dir=args.input_dir,
        mapping_file=args.mapping,
        client=client,
        dry_run=dry_run,
        enabled_only=args.enabled_only
    )

    importer.import_all()


if __name__ == "__main__":
    main()
